# Splunk Server particulars

host: "localhost"
# Splunkd Management port
port: 8089
username: "admin"
password: "admin"
usessl: true

# number of concurrent tasks
numberOfThreads: 5

#prefix used to show up metrics in AppDynamics
metricPrefix:  "Custom Metrics|Splunk|"

searchKeywords: 
     - keyword: "Splunk"
       displayName: "Splunk"
       host: ""
       source: ""
       sourcetype: ""
       index: ""
       
     - keyword: "Controller"
       displayName: "Controller"
       host: ""
       source: ""
       sourcetype: ""
       index: ""
